### ISSUE TITLE
Migrate to exist Entity

### ISSUE THREAD

**Issue by cleanDevil** [Tanya-WebDev/file-manager#1]
Hi,
it's not an Issue, but a Question.
Is it possible to configure the Filemanager to an existing Entity?
I'm not a developer and hope, you can give me some Tips, how to do that.

Your Filemanager ist a great App, easy to use and nor overloaded.
Thanks for Publishing ...

Best

**Comment by Tanya-WebDev** [comment]
Hi. Yes, of course you can! Describe the problem in more detail and I will help you.

**Comment by cleanDevil** [comment]
Hi Tanya,
thank you for your reply and your offered support.
What exactly do you need to know?
Basics:
I created an entity class and created the forms with "php bin/console make:crud" that stores all queries (via form) in a MySQL database, but files should also be able to be uploaded per ID.
Do you need more information?

Best, Maiko

**Comment by Tanya-WebDev** [comment]
To be honest, I don't quite understand. I have a form in the lesson that simply allows you to upload a file, parses the data about the file and displays it in a table after the file has been successfully uploaded. This file can be downloaded or deleted.

What does your application do? What functionality do you want to implement? I don't understand why you want to upload a file by ID? Is it something like a User's page, where it is possible to upload a photo to this page at any time? Just write down the logic. Because I do not quite understand what you are doing and what difficulties you are facing.

**Comment by cleanDevil** [comment]
Sorry for my confusing description.

following scenario:
I have created a form in which I have various queries (e.g. title, description) and I would also like to enable a file upload that only refers to this data record.
I would like to realize this with your file manager.

**Comment by Tanya-WebDev** [comment]
I think in this case it would be easiest for you to store everything in a single Entity: Title, Description, and the file data. This way, you won't need to make many code adjustments.

If you don't have strict requirements for data normalization and no plans to expand the database schema in the future, storing all the data in a single entity can be a very convenient and straightforward solution.

**But there's also an alternative approach:**

1. Store Title and Description in one table, and data about the uploaded file in another table. You can use a separate table to establish a relationship between them.

This approach involves creating an additional table in the database, which serves to link two (or more) other tables. For instance, if you have a table for records and another for files, you can create a third table that only contains two columns: Record ID and File ID. This table would serve to establish a relationship between records and files.

This approach is more normalized and allows for more flexible data management. It reduces data duplication and facilitates potential future changes. You won't need to store identical data (e.g., Title and Description) for each file, which can help reduce the database size and make its usage more efficient.

2. Another approach is to rename the uploaded file during the upload process and assign it a generated ID as its name. This way, you can correlate the record's ID from the database with the file name.

This approach can also be a good solution, especially if you don't want to create complex relationships between tables and prefer to keep everything within a single entity. It simplifies the logic and connection between files and records, as you can use the record's ID as part of the file name for unique identification.

**Comment by cleanDevil** [comment]
Hello Tanya,

thanks for your suggestions
I'll think about it and test it as needed.
Thank you for your time and effort.

Greetings Maiko

**Comment by Tanya-WebDev** [comment]
You are welcome! :) And good luck!
